// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxpL1sfA0nOhwBQQd6OuudGAWRiQ0xHDc',
    appId: '1:423294092110:web:d8403d1ce7dd6c1783541f',
    messagingSenderId: '423294092110',
    projectId: 'estudia-49956',
    authDomain: 'estudia-49956.firebaseapp.com',
    storageBucket: 'estudia-49956.firebasestorage.app',
    measurementId: 'G-84VHPHQ3NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJor7Pk9oVbgakZovTCjkoO6aBwr1nlWQ',
    appId: '1:423294092110:android:9006b5da48ea204c83541f',
    messagingSenderId: '423294092110',
    projectId: 'estudia-49956',
    storageBucket: 'estudia-49956.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwPrciGhVpm2qz2j5zbiOkpOZ6A87bzoE',
    appId: '1:423294092110:ios:9be5c8001634a93183541f',
    messagingSenderId: '423294092110',
    projectId: 'estudia-49956',
    storageBucket: 'estudia-49956.firebasestorage.app',
    iosBundleId: 'com.example.estudia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwPrciGhVpm2qz2j5zbiOkpOZ6A87bzoE',
    appId: '1:423294092110:ios:9be5c8001634a93183541f',
    messagingSenderId: '423294092110',
    projectId: 'estudia-49956',
    storageBucket: 'estudia-49956.firebasestorage.app',
    iosBundleId: 'com.example.estudia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxpL1sfA0nOhwBQQd6OuudGAWRiQ0xHDc',
    appId: '1:423294092110:web:0db108eb628efb3083541f',
    messagingSenderId: '423294092110',
    projectId: 'estudia-49956',
    authDomain: 'estudia-49956.firebaseapp.com',
    storageBucket: 'estudia-49956.firebasestorage.app',
    measurementId: 'G-1ZDCLWN81T',
  );
}